spark.StreamingApp.kafkaBrokers: "10.85.122.195:9092,10.85.129.154:9092,10.85.117.179:9092"
spark.StreamingApp.repartition: true
spark.StreamingApp.numPartitions: 100
spark.KAFKA_CONSUMER.groupId: "spark-streaming"
spark.KAFKA_CONSUMER.host: "10.85.140.132:2181,10.85.111.110:2181,10.85.132.52:2181,10.85.132.77:2181,10.85.125.244:2181"
spark.StreamingApp.max.cores: 100
spark.Streaming.env: "prod"
spark.StreamingApp.appName: "spark-real-event"
spark.Tasks.App.Interval: 120
spark.StreamingApp.sparkMaster: "spark://10.85.123.127:7077,10.85.129.87:7077,10.85.110.138:7077"
spark.StreamingApp.executor.memory: 5g
spark.StreamingApp.unpersist: true
spark.StreamingApp.es.nodes: ""
spark.StreamingApp.es.port: ""
spark.StreamingApp.es.timeout: 1000
spark.StreamingApp.es.autocreate: false
spark.StreamingApp.kafka.maxRatePerPartition: 20
userBooking.kafka.topic: ""
spark.StreamingApp.userBookingPartition: 1
driverEvent.kafka.topic: ""
spark.streamingApp.driverEventPartition: 1
spark.Streaming.es.UserIndex: "user"